# Copyright 2025 DeepMind Technologies Limited
# Copyright 2025 Antoine Pirrone - Steve Nguyen
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Modified 2026 (Open Duck Mini v2 term project):
#   New file, derived from `joystick.py` of this project. Replaces the
#   joystick locomotion task with a get-up task that keeps the episode
#   alive after a fall so recovery can be learned.
# ==============================================================================
"""Get-up (standup) task for Open Duck Mini V2.

The shipped `joystick` task terminates the episode the moment the robot tips
over (`fall_termination`), so its policies have never experienced being on the
ground and cannot recover from a fall. This task trains that missing skill.

Three things had to change:

1.  Collision geometry.  In the stock model the only geoms that collide are the
    two TPU foot soles, so a fallen robot sinks through the floor and there is
    nothing to push against.  `scene_standup.xml` (generated by
    `make_standup_xml.py`) adds ground-only collision boxes to the trunk, head,
    shins and thighs.
2.  Termination.  `fall_termination` is dropped; only NaNs end an episode.
3.  Rewards.  Velocity tracking and gait imitation are replaced by "get the
    torso upright" and "get the torso high".

The observation layout is deliberately left untouched (inherited `_get_obs`),
so a policy trained here loads in `mujoco_infer.py` exactly like a walking one:

    python -m playground.open_duck_mini_v2.mujoco_infer \
        -o <standup.onnx> \
        --model_path playground/open_duck_mini_v2/xmls/scene_standup.xml
"""

from typing import Any, Dict, Optional, Union

import jax
import jax.numpy as jp
from ml_collections import config_dict
from mujoco import mjx
from mujoco.mjx._src import math

from mujoco_playground._src import mjx_env
from mujoco_playground._src.collision import geoms_colliding

from . import constants
from . import base as open_duck_mini_v2_base
from .joystick import Joystick, default_config as joystick_default_config

from playground.common.rewards import (
    cost_ang_vel_xy,
    cost_torques,
    cost_action_rate,
    reward_alive,
)

STANDUP_XML = constants.ROOT_PATH / "xmls" / "scene_standup.xml"

# Height the base is dropped from at reset, and the height that counts as
# "fully stood up". The home keyframe puts the base at 0.15 m.
DROP_HEIGHT = 0.22
TARGET_HEIGHT = 0.15

# Range of tilt applied at reset, in radians: 20 to 180 degrees.
#
# Spawning only past horizontal (the obvious reading of "get up from a fall")
# turns out to be the wrong call. Random exploration never completes a full
# recovery from flat on the back, so the policy never sees a success and there
# is no gradient to follow - trained that way it just lies still.
#
# Sampling the whole range instead gives a curriculum for free. A 20 degree tilt
# is recovered by a small correction, which exploration does find, and that
# reward pulls the policy toward the harder starts. It also matches what the
# robot actually meets in use: stumbles, shoves and walking into things are far
# more common than ending up flat on its back.
MIN_FALL_ANGLE = 0.35
MAX_FALL_ANGLE = 3.14159


def default_config() -> config_dict.ConfigDict:
    """Joystick config with the reward set swapped out for get-up terms."""
    config = joystick_default_config()

    config.reward_config.scales = config_dict.create(
        # Dominant term: the torso's own z axis should point at the sky.
        upright=5.0,
        # Secondary: actually rise, rather than lying flat but face-up.
        height=3.0,
        # The missing rung on the ladder. Torso-upright and torso-high say
        # nothing about the step that actually matters in between - rolling over
        # and getting the feet underneath you. Without it the policy thrashes
        # without ever organising the motion.
        feet_contact=1.5,
        # Anti-thrash, gated on being upright. Nothing else in this set damps
        # torso rotation, so the policy learned to flail; it reaches upright and
        # then shakes itself over. Ungated this would fight the roll-over, which
        # needs angular velocity.
        ang_vel_xy=-0.3,
        # Small, unlike joystick's 20.0. There is no fall termination here, so a
        # large alive bonus would just pay the robot to lie still and wait.
        alive=0.5,
        torques=-1.0e-3,
        # Relaxed from joystick's -0.5 because standing up needs large, fast
        # motions - but -0.1 turned out to be too loose and left the gait jittery
        # even once upright.
        action_rate=-0.2,
        # "Come to attention": how close the joints are to the home pose, and
        # how still they are, once the robot is up.
        #
        # These replace cost_stand_still, which is an unbounded sum over 14
        # joints of position error plus velocity. At -0.3 it reached -13.9 while
        # the robot was moving, which flipped the total negative: standing up
        # requires vigorous motion, so the instant the policy got upright it was
        # punished harder than for lying still (+0.50 vs 0.00 after clipping).
        # It learned the obvious lesson and stayed down. Bounded 0..1 rewards
        # cannot invert that ordering no matter how they are weighted.
        attention=2.0,
        stillness=1.0,
    )

    # Random shoves would fight the get-up motion while it is still being
    # learned. Re-enable once a first policy works.
    config.push_config.enable = False

    # 500 * 0.02 s = 10 s, ample for a single get-up attempt.
    config.episode_length = 500

    return config


class Standup(Joystick):
    """Recover from an arbitrary fallen pose and stand up."""

    def __init__(
        self,
        task: str = "standup",
        config: Optional[config_dict.ConfigDict] = None,
        config_overrides: Optional[Dict[str, Union[str, int, list[Any]]]] = None,
    ):
        del task  # This task always uses the standup scene.
        # Skip Joystick.__init__, which would resolve the XML through
        # constants.task_to_xml(); go straight to the base env with our scene.
        open_duck_mini_v2_base.OpenDuckMiniV2Env.__init__(
            self,
            xml_path=STANDUP_XML.as_posix(),
            config=default_config() if config is None else config,
            config_overrides=config_overrides,
        )
        self._post_init()

    # -- no velocity commands in this task -------------------------------------

    def sample_command(self, rng: jax.Array) -> jax.Array:
        """Always zero.

        Overriding this covers both the draw in `reset` and the periodic
        re-draw in `step`, so the command slice of the observation stays zero
        for the whole episode.
        """
        return jp.zeros_like(super().sample_command(rng))

    # -- start the episode on the ground ---------------------------------------

    def reset(self, rng: jax.Array) -> mjx_env.State:
        # Let Joystick build a complete, valid state (info dict, metrics keys,
        # reference motion, push schedule), then re-init the physics from a
        # fallen pose.
        state = super().reset(rng)
        info = dict(state.info)
        rng, k_axis, k_angle = jax.random.split(info["rng"], 3)

        addr = self._floating_base_qpos_addr
        qpos = state.data.qpos

        # Tilt by a random angle about a random *horizontal* axis. The axis has
        # to lie in the xy plane: a rotation about anything close to vertical
        # only yaws the robot and leaves it standing, so the sampled angle would
        # stop meaning anything. With a horizontal axis the torso tilts by
        # exactly `angle`, which is what makes the curriculum above work, and the
        # uniform direction spreads the landings over back, front and both sides.
        phi = jax.random.uniform(k_axis, (), minval=0.0, maxval=2.0 * jp.pi)
        axis = jp.array([jp.cos(phi), jp.sin(phi), 0.0])
        angle = jax.random.uniform(k_angle, (), minval=MIN_FALL_ANGLE, maxval=MAX_FALL_ANGLE)
        qpos = qpos.at[addr + 3 : addr + 7].set(
            math.quat_mul(qpos[addr + 3 : addr + 7], math.axis_angle_to_quat(axis, angle))
        )
        qpos = qpos.at[addr + 2].set(DROP_HEIGHT)

        qvel = jp.zeros(self.mjx_model.nv)
        ctrl = self.get_actuator_joints_qpos(qpos)
        data = mjx_env.init(self.mjx_model, qpos=qpos, qvel=qvel, ctrl=ctrl)

        info["rng"] = rng
        contact = jp.array(
            [
                geoms_colliding(data, geom_id, self._floor_geom_id)
                for geom_id in self._feet_geom_id
            ]
        )
        obs = self._get_obs(data, info, contact)
        return mjx_env.State(
            data, obs, jp.zeros(()), jp.zeros(()), state.metrics, info
        )

    # -- never end the episode for falling -------------------------------------

    def _get_termination(self, data: mjx.Data) -> jax.Array:
        # Joystick ends the episode as soon as the torso passes horizontal.
        # Keeping that here would make the task unlearnable: the robot would be
        # reset before it ever got a chance to push itself back up.
        return jp.isnan(data.qpos).any() | jp.isnan(data.qvel).any()

    # -- rewards ---------------------------------------------------------------

    def _get_reward(
        self,
        data: mjx.Data,
        action: jax.Array,
        info: dict[str, Any],
        metrics: dict[str, Any],
        done: jax.Array,
        first_contact: jax.Array,
        contact: jax.Array,
    ) -> dict[str, jax.Array]:
        del metrics, done, first_contact  # Unused.

        # "upvector" sensor: the IMU site's z axis expressed in world frame.
        # +1 when the torso is upright, -1 when it is inverted.
        up = self.get_gravity(data)[-1]
        height = self.get_floating_base_qpos(data.qpos)[2]

        # How upright the torso is, as a 0..1 weight. Used instead of a boolean
        # `up > 0` test so the terms below fade in and out smoothly; a hard
        # threshold puts a cliff in the reward right around horizontal, which is
        # exactly where the robot spends its time while trying to get up.
        uprightness = jp.clip(up, 0.0, 1.0)
        # Settling terms switch on over the top half of the range, so they ask
        # for stillness only once the robot is nearly there.
        settled = jp.clip((up - 0.5) * 2.0, 0.0, 1.0)

        return {
            "upright": (up + 1.0) * 0.5,
            # Scaled by uprightness, otherwise balancing on the head would score
            # as well as standing on the feet.
            "height": jp.clip(height / TARGET_HEIGHT, 0.0, 1.0) * uprightness,
            # Feet down counts for more the more upright the torso is, so the
            # policy is pulled toward "feet under me, torso up" rather than
            # toward lying on its back with its soles against the floor.
            "feet_contact": jp.sum(contact) / 2.0 * uprightness,
            "ang_vel_xy": cost_ang_vel_xy(self.get_global_angvel(data)) * settled,
            "alive": reward_alive(),
            "torques": cost_torques(data.actuator_force),
            "action_rate": cost_action_rate(action, info["last_act"]),
            # Bounded 0..1: 1.0 at the home pose, decaying with mean joint
            # error. Gated so it only shapes the final pose, never the get-up.
            "attention": jp.exp(-4.0 * jp.mean(jp.abs(
                self.get_actuator_joints_qpos(data.qpos) - self._default_actuator
            ))) * settled,
            # Bounded 0..1: 1.0 when the joints have stopped.
            "stillness": jp.exp(-0.5 * jp.mean(jp.abs(
                self.get_actuator_joints_qvel(data.qvel)
            ))) * settled,
        }
