# Copyright 2025 DeepMind Technologies Limited
# Copyright 2025 Antoine Pirrone - Steve Nguyen
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Modified 2026 (Open Duck Mini v2 term project):
#   New file, derived from `joystick.py` of this project. Replaces the
#   joystick locomotion task with a get-up task that keeps the episode
#   alive after a fall so recovery can be learned.
# ==============================================================================
"""Get-up (standup) task for Open Duck Mini V2.

The shipped `joystick` task terminates the episode the moment the robot tips
over (`fall_termination`), so its policies have never experienced being on the
ground and cannot recover from a fall. This task trains that missing skill.

Three things had to change:

1.  Collision geometry.  In the stock model the only geoms that collide are the
    two TPU foot soles, so a fallen robot sinks through the floor and there is
    nothing to push against.  `scene_standup.xml` (generated by
    `make_standup_xml.py`) adds ground-only collision boxes to the trunk, head,
    shins and thighs.
2.  Termination.  `fall_termination` is dropped; only NaNs end an episode.
3.  Rewards.  Velocity tracking and gait imitation are replaced by "get the
    torso upright" and "get the torso high".

The observation layout is deliberately left untouched (inherited `_get_obs`),
so a policy trained here loads in `mujoco_infer.py` exactly like a walking one:

    python -m playground.open_duck_mini_v2.mujoco_infer \
        -o <standup.onnx> \
        --model_path playground/open_duck_mini_v2/xmls/scene_standup.xml
"""

import os
from typing import Any, Dict, Optional, Union

import jax
import jax.numpy as jp
import numpy as np
from ml_collections import config_dict
from mujoco import mjx

from mujoco_playground._src import mjx_env
from mujoco_playground._src.collision import geoms_colliding

from . import constants
from . import base as open_duck_mini_v2_base
from .joystick import Joystick, default_config as joystick_default_config

from playground.common.rewards import (
    cost_ang_vel_xy,
    cost_torques,
    cost_action_rate,
    reward_alive,
)

STANDUP_XML = constants.ROOT_PATH / "xmls" / "scene_standup.xml"

# Settled fallen poses, generated offline by `make_standup_poses.py`. See
# `reset` for why the episode starts from a table instead of a live drop.
POSE_BANK = constants.ROOT_PATH / "data" / "standup_poses.npy"

# States sampled along a get-up trajectory that works, found by direct
# trajectory optimisation (`standup_feasibility.py`) and expanded into states by
# `make_standup_refstates.py`. Each row is [qpos | qvel].
REF_STATES = constants.ROOT_PATH / "data" / "standup_refstates.npy"

# Fraction of episodes that start part-way through that trajectory instead of
# flat on the floor.
#
# Reward shaping alone does not get this task off the ground - v5 trained for
# 300M steps on the fixed rewards and still scored 0/120. Replaying the known
# solution shows why, and it is not something a reward can fix: the trajectory
# passes through up = -0.70 on its way to up = +0.84. Getting up requires first
# becoming *more* inverted, and `upright` at weight 5.0 punishes exactly that.
# Any reward monotone in uprightness makes the solution a valley the policy has
# to cross, and Gaussian action noise does not cross four seconds of coordinated
# motion by luck.
#
# Starting some episodes near the end of the trajectory sidesteps the search
# entirely: the policy learns to finish from almost-standing, and the value
# function carries that backwards into the hard part. Half and half, because
# training only on reference states teaches the tail and never the task - the
# start distribution the policy is actually scored on is the pose bank.
#
# Overridable from the environment so one visit to the cluster can launch a
# sweep; the runner has no seed or hyper-parameter arguments and `runner.py` is
# diverged on the server, so an env var is the only knob that does not mean
# shipping a shared file.
REF_FRACTION = float(os.environ.get("REF_FRACTION", "0.5"))

# The height that counts as "fully stood up"; the home keyframe puts the base
# at 0.15 m.
TARGET_HEIGHT = 0.15

# Collision boxes that must leave the floor for the robot to be off the ground.
# Knees and shins are deliberately excluded: kneeling is a legitimate - in fact
# necessary - stage of getting up, so penalising knee contact would punish the
# one intermediate posture the task is trying to reach.
BODY_GEOMS = ("trunk_assembly_ground_collision", "head_assembly_ground_collision")

# Height at which the body counts as fully clear of the floor, in metres.
# Standing puts the bottom of the trunk box about 0.12 m up, so this saturates
# well before the robot is upright and keeps paying during the kneel.
CLEAR_HEIGHT = 0.05


def default_config() -> config_dict.ConfigDict:
    """Joystick config with the reward set swapped out for get-up terms."""
    config = joystick_default_config()

    config.reward_config.scales = config_dict.create(
        # Dominant term: the torso's own z axis should point at the sky.
        upright=5.0,
        # Secondary: actually rise, rather than lying flat but face-up.
        height=3.0,
        # The missing rung on the ladder. Torso-upright and torso-high say
        # nothing about the step that actually matters in between - rolling over
        # and getting the feet underneath you. Without it the policy thrashes
        # without ever organising the motion.
        feet_contact=1.5,
        # Push the body off the floor.
        #
        # Measured on the v2/v3/v4 policies with `eval_standup.py`: from any
        # start past 45 degrees they reach a lying pose and stop there, scoring
        # upright 0.5 and everything else 0. The reason is that every other term
        # is gated on `uprightness`, which is 0 while the torso is horizontal -
        # so the whole first half of getting up (tuck the legs, plant the feet,
        # press the trunk off the ground) pays exactly nothing, and the policy
        # settles for lying still. This term is the one thing that does pay
        # during that phase, and unlike raw height it cannot be farmed by lying
        # inverted on the head plate.
        ground_clear=2.0,
        # Anti-thrash, gated on being upright. Nothing else in this set damps
        # torso rotation, so the policy learned to flail; it reaches upright and
        # then shakes itself over. Ungated this would fight the roll-over, which
        # needs angular velocity.
        ang_vel_xy=-0.3,
        # Small, unlike joystick's 20.0. There is no fall termination here, so a
        # large alive bonus would just pay the robot to lie still and wait.
        alive=0.5,
        torques=-1.0e-3,
        # Relaxed from joystick's -0.5 because standing up needs large, fast
        # motions - but -0.1 turned out to be too loose and left the gait jittery
        # even once upright.
        action_rate=-0.2,
        # "Come to attention": how close the joints are to the home pose, and
        # how still they are, once the robot is up.
        #
        # These replace cost_stand_still, which is an unbounded sum over 14
        # joints of position error plus velocity. At -0.3 it reached -13.9 while
        # the robot was moving, which flipped the total negative: standing up
        # requires vigorous motion, so the instant the policy got upright it was
        # punished harder than for lying still (+0.50 vs 0.00 after clipping).
        # It learned the obvious lesson and stayed down. Bounded 0..1 rewards
        # cannot invert that ordering no matter how they are weighted.
        attention=2.0,
        stillness=1.0,
    )

    # Random shoves would fight the get-up motion while it is still being
    # learned. Re-enable once a first policy works.
    config.push_config.enable = False

    # 500 * 0.02 s = 10 s, ample for a single get-up attempt.
    config.episode_length = 500

    return config


class Standup(Joystick):
    """Recover from an arbitrary fallen pose and stand up."""

    def __init__(
        self,
        task: str = "standup",
        config: Optional[config_dict.ConfigDict] = None,
        config_overrides: Optional[Dict[str, Union[str, int, list[Any]]]] = None,
    ):
        del task  # This task always uses the standup scene.
        # Skip Joystick.__init__, which would resolve the XML through
        # constants.task_to_xml(); go straight to the base env with our scene.
        open_duck_mini_v2_base.OpenDuckMiniV2Env.__init__(
            self,
            xml_path=STANDUP_XML.as_posix(),
            config=default_config() if config is None else config,
            config_overrides=config_overrides,
        )
        self._post_init()

        self._body_geom_id = np.array(
            [self._mj_model.geom(name).id for name in BODY_GEOMS]
        )
        self._body_geom_half = jp.asarray(self._mj_model.geom_size[self._body_geom_id])
        if not POSE_BANK.exists():
            raise FileNotFoundError(
                f"{POSE_BANK} is missing. Generate it first:\n"
                "    python make_standup_poses.py"
            )
        fallen = np.load(POSE_BANK.as_posix())
        if fallen.shape[1] != self.mjx_model.nq:
            raise ValueError(
                f"{POSE_BANK} holds qpos of width {fallen.shape[1]}, but this model "
                f"has nq={self.mjx_model.nq}. Regenerate the bank against the same XML."
            )
        self._fallen_qpos = jp.asarray(fallen)

        if not REF_STATES.exists():
            raise FileNotFoundError(
                f"{REF_STATES} is missing. Generate it first:\n"
                "    python make_standup_refstates.py"
            )
        ref = np.load(REF_STATES.as_posix())
        want = self.mjx_model.nq + self.mjx_model.nv
        if ref.shape[1] != want:
            raise ValueError(
                f"{REF_STATES} holds rows of width {ref.shape[1]}, but this model wants "
                f"nq+nv={want}. Regenerate it against the same XML."
            )
        self._ref_qpos = jp.asarray(ref[:, : self.mjx_model.nq])
        self._ref_qvel = jp.asarray(ref[:, self.mjx_model.nq :])

    # -- no velocity commands in this task -------------------------------------

    def sample_command(self, rng: jax.Array) -> jax.Array:
        """Always zero.

        Overriding this covers both the draw in `reset` and the periodic
        re-draw in `step`, so the command slice of the observation stays zero
        for the whole episode.
        """
        return jp.zeros_like(super().sample_command(rng))

    # -- start the episode on the ground ---------------------------------------

    def reset(self, rng: jax.Array) -> mjx_env.State:
        """Start the episode genuinely lying on the floor.

        The previous version built the start pose live: tilt the home keyframe by
        a random angle about a random horizontal axis, set the base to 0.22 m,
        begin. Three things were wrong with it, all found by actually settling
        those poses and looking at them (`standup_feasibility.py` prints the
        survey):

        1.  The episode began in mid-air. The robot spent the first third of a
            second falling, so "start from lying down" was never what was being
            trained.
        2.  The tilt angle barely mattered. Every start between 90 and 160
            degrees settles into the *same* pose (up 0.00, base 14.7 cm, trunk
            box on the floor). The wide angle range was meant to be a curriculum;
            in practice it dealt the same hand over and over.
        3.  At exactly 180 degrees the robot lands on its head plate - 20x20 cm,
            flat - and stays there, balanced upside down with its feet 35 cm in
            the air. That is not a fallen robot, it is a headstand, and it only
            exists because a perfectly inverted body is dropped at zero velocity
            onto a flat plate. The hardest end of the curriculum was an artefact.

        So the falls are now simulated offline instead, with random tilt, random
        joint offsets and a random shove, and only poses that have come to rest
        are kept. `reset` draws from that table. Sampling a real distribution of
        resting poses is also what makes the start states diverse in the way the
        angle sweep was supposed to be.
        """
        # Let Joystick build a complete, valid state (info dict, metrics keys,
        # reference motion, push schedule), then re-init the physics from a
        # fallen pose.
        state = super().reset(rng)
        info = dict(state.info)
        rng, k_pose, k_joint, k_ref, k_mode = jax.random.split(info["rng"], 5)

        fallen = self._fallen_qpos[
            jax.random.randint(k_pose, (), 0, self._fallen_qpos.shape[0])
        ]
        # The other half of the draw: a state part-way along a get-up that
        # works. See REF_FRACTION for why this is here rather than a reward.
        i_ref = jax.random.randint(k_ref, (), 0, self._ref_qpos.shape[0])
        use_ref = jax.random.uniform(k_mode, ()) < REF_FRACTION

        qpos = jp.where(use_ref, self._ref_qpos[i_ref], fallen)
        # Reference states carry momentum, and dropping it would start the
        # episode in a pose that the trajectory never actually passes through -
        # mid-roll with zero angular velocity is a different problem. Poses from
        # the bank have already come to rest, so zero is right for those.
        qvel = jp.where(use_ref, self._ref_qvel[i_ref], jp.zeros(self.mjx_model.nv))

        # A little joint jitter on top, so the policy cannot memorise the table
        # entries. Kept small: the bank poses are resting in contact, and a large
        # perturbation would start the episode with the feet driven through the
        # floor.
        joints = self.get_actuator_joints_qpos(qpos)
        qpos = self.set_actuator_joints_qpos(
            joints + jax.random.normal(k_joint, joints.shape) * 0.02, qpos
        )
        ctrl = self.get_actuator_joints_qpos(qpos)
        data = mjx_env.init(self.mjx_model, qpos=qpos, qvel=qvel, ctrl=ctrl)

        info["rng"] = rng
        contact = jp.array(
            [
                geoms_colliding(data, geom_id, self._floor_geom_id)
                for geom_id in self._feet_geom_id
            ]
        )
        obs = self._get_obs(data, info, contact)
        return mjx_env.State(
            data, obs, jp.zeros(()), jp.zeros(()), state.metrics, info
        )

    # -- never end the episode for falling -------------------------------------

    def _get_termination(self, data: mjx.Data) -> jax.Array:
        # Joystick ends the episode as soon as the torso passes horizontal.
        # Keeping that here would make the task unlearnable: the robot would be
        # reset before it ever got a chance to push itself back up.
        return jp.isnan(data.qpos).any() | jp.isnan(data.qvel).any()

    # -- rewards ---------------------------------------------------------------

    def _get_reward(
        self,
        data: mjx.Data,
        action: jax.Array,
        info: dict[str, Any],
        metrics: dict[str, Any],
        done: jax.Array,
        first_contact: jax.Array,
        contact: jax.Array,
    ) -> dict[str, jax.Array]:
        del metrics, done, first_contact  # Unused.

        # "upvector" sensor: the IMU site's z axis expressed in world frame.
        # +1 when the torso is upright, -1 when it is inverted.
        up = self.get_gravity(data)[-1]
        height = self.get_floating_base_qpos(data.qpos)[2]

        # How upright the torso is, as a 0..1 weight. Used instead of a boolean
        # `up > 0` test so the terms below fade in and out smoothly; a hard
        # threshold puts a cliff in the reward right around horizontal, which is
        # exactly where the robot spends its time while trying to get up.
        uprightness = jp.clip(up, 0.0, 1.0)
        # Settling terms switch on over the top half of the range, so they ask
        # for stillness only once the robot is nearly there.
        settled = jp.clip((up - 0.5) * 2.0, 0.0, 1.0)

        # How far the body is off the floor, as a 0..1 weight. This is the one
        # signal that is available while the robot is still horizontal, and it is
        # what turns "lie still" from a local optimum into a losing move.
        #
        # Measured as the lowest corner of the trunk and head boxes rather than
        # as a contact test. A contact test was the first attempt and it is
        # wrong twice over: `geoms_colliding` only fires on actual penetration,
        # so 38% of the settled lying poses in the bank read as "clear" and
        # collected the bonus for lying down (measured - `smoke_standup.py`
        # step 7 catches it); and being binary it pays nothing for lifting the
        # body 4 cm, which is exactly the increment the policy has to discover.
        # Geometry has neither problem: it is margin-free and it is continuous.
        pos = data.geom_xpos[self._body_geom_id]
        mat = data.geom_xmat[self._body_geom_id].reshape(-1, 3, 3)
        # World-z half-extent of an oriented box: |R_z . h| summed per axis.
        drop = jp.sum(jp.abs(mat[:, 2, :]) * self._body_geom_half, axis=-1)
        ground_clear = jp.clip(jp.min(pos[:, 2] - drop) / CLEAR_HEIGHT, 0.0, 1.0)

        return {
            "upright": (up + 1.0) * 0.5,
            # Scaled by uprightness, otherwise balancing on the head would score
            # as well as standing on the feet.
            "height": jp.clip(height / TARGET_HEIGHT, 0.0, 1.0) * uprightness,
            # Gated on the body being off the floor rather than on uprightness.
            #
            # Gating on uprightness was meant to stop the robot scoring for
            # lying on its back with its soles against the floor, and it does -
            # but it also zeroes the term throughout the half of the motion
            # where planting the feet is the whole job. `ground_clear` rules out
            # the same cheat (on your back, the trunk box is down, so the gate is
            # 0) while paying for the posture that actually leads somewhere:
            # feet on the floor, body off it. That is a kneel, and a kneel is
            # one push away from standing.
            "feet_contact": jp.sum(contact) / 2.0 * ground_clear,
            "ground_clear": ground_clear,
            "ang_vel_xy": cost_ang_vel_xy(self.get_global_angvel(data)) * settled,
            "alive": reward_alive(),
            "torques": cost_torques(data.actuator_force),
            "action_rate": cost_action_rate(action, info["last_act"]),
            # Bounded 0..1: 1.0 at the home pose, decaying with mean joint
            # error. Gated so it only shapes the final pose, never the get-up.
            "attention": jp.exp(-4.0 * jp.mean(jp.abs(
                self.get_actuator_joints_qpos(data.qpos) - self._default_actuator
            ))) * settled,
            # Bounded 0..1: 1.0 when the joints have stopped.
            "stillness": jp.exp(-0.5 * jp.mean(jp.abs(
                self.get_actuator_joints_qvel(data.qvel)
            ))) * settled,
        }
